require_relative '../config/environment.rb'

u1 = User.new('Pete')
u2 = User.new('Tristram')
u3 = User.new('Russell')
u4 = User.new('Evans')
u5 = User.new('Andrew')
u6 = User.new('Vicky')
u7 = User.new('Dick')

r1 = Recipe.new('Drywall Lasagna')
r2 = Recipe.new('Lego Pizza')
r3 = Recipe.new('Worcestershire Sauce Cake')
r4 = Recipe.new('Spork Soup')
r5 = Recipe.new('Potato Ice Cream')

i1 = Ingredient.new('Celery')
i2 = Ingredient.new('Mouse Eyes')
i3 = Ingredient.new('Squid Testicles')
i4 = Ingredient.new('Lard')
i5 = Ingredient.new('Cow Intestines')
i6 = Ingredient.new('Cotton Candy')
i7 = Ingredient.new('Tears of Tibetan Yaks')

a1 = Allergen.new(u2, i3)
a2 = Allergen.new(u4, i4)
a3 = Allergen.new(u1, i3)
a4 = Allergen.new(u7, i7)
a5 = Allergen.new(u5, i1)
a6 = Allergen.new(u3, i1)
a7 = Allergen.new(u2, i6)

ri1 = RecipeIngredient.new(i2, r1)
ri2 = RecipeIngredient.new(i3, r1)
ri3 = RecipeIngredient.new(i7, r2)
ri4 = RecipeIngredient.new(i5, r2)
ri5 = RecipeIngredient.new(i2, r3)
ri6 = RecipeIngredient.new(i6, r3)
ri7 = RecipeIngredient.new(i1, r4)
ri8 = RecipeIngredient.new(i5, r4)
ri9 = RecipeIngredient.new(i1, r5)
ri10 = RecipeIngredient.new(i4, r5)

rc1 = RecipeCard.new(u1, r1, "07/16", 4)
rc2 = RecipeCard.new(u2, r2, "07/16", 2)
rc3 = RecipeCard.new(u3, r3, "07/16", 2)
rc4 = RecipeCard.new(u4, r4, "07/16", 2)
rc5 = RecipeCard.new(u5, r5, "07/16", 5)
rc7 = RecipeCard.new(u6, r5, "07/16", 3)
rc8 = RecipeCard.new(u3, r2, "07/16", 1)
rc9 = RecipeCard.new(u2, r3, "07/16", 5)
rc10 = RecipeCard.new(u1, r4, "07/16", 3)

binding.pry
